In [10]:
#importing the needed packages
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

In [11]:
#loading the dataset

data=pd.DataFrame(pd.read_csv("MoviesData.csv"))

data.head()

Titles Rating  RTCritic  ...  Horror  Mystery  Documentary
0  Treasure Planet     PG        69  ...       0        0            0
1    About Schmidt      R        85  ...       0        0            0
2        Secretary      R        76  ...       0        0            0
3     Irreversible     NR        57  ...       0        0            0
4      Big Trouble   PG13        48  ...       0        0            0

[5 rows x 19 columns]

In [12]:
#dimensions of the dataset
data.shape

(225, 19)

In [13]:
#checking whether there is any null values
data.isnull().sum()

Titles           0
Rating           0
RTCritic         0
RTFan            0
IMDb             0
Metacritic       0
BoxOffice        0
Year             0
Action           0
Animation        0
Family           0
Scifi            0
Comedy           0
Drama            0
International    0
Romance          0
Horror           0
Mystery          0
Documentary      0
dtype: int64

In [14]:
#droping the data column 

data.drop(['Rating'],axis=1,inplace=True)

In [15]:
#dimesions after droping
data.shape

(225, 18)

In [17]:
#x and y 
Y=data.pop('IMDb')

X=data

In [19]:
#droping the data column 

data.drop(['Titles'],axis=1,inplace=True)

In [20]:
#train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y,train_size=0.7, test_size=0.3, random_state=0)

In [21]:
#performing normal mr
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
#predicting the result
pred = model.predict(X_test)
pred

array([6.63623908, 5.46409778, 5.66889368, 7.14646581, 4.56976037,
       7.55307244, 5.51045148, 7.58283391, 6.13084899, 8.11357016,
       4.84855555, 7.90260019, 7.74410697, 5.37983381, 6.30312716,
       6.02768854, 4.6450526 , 6.2938491 , 7.09659518, 6.48589862,
       5.14143999, 7.37266164, 5.57503688, 6.57289674, 7.02122859,
       4.69084889, 4.70093546, 6.4757857 , 5.74167963, 6.51093739,
       5.28783545, 6.55271971, 5.71223055, 6.72356374, 6.50407606,
       4.8243387 , 6.69811554, 6.72776142, 6.00273743, 7.66133677,
       7.44548268, 6.25617582, 5.18047623, 6.09880493, 7.64463257,
       5.75234096, 5.58955686, 7.36703121, 5.74608932, 4.93639789,
       7.08665441, 4.91656196, 4.92284355, 6.68585552, 5.45386152,
       8.04265266, 7.64584364, 5.95693508, 7.55412742, 4.62169594,
       4.89923201, 7.65151787, 5.93680469, 5.631358  , 6.10073011,
       6.21963443, 6.47339492, 5.62161319])

In [23]:
#y_test
#y_test.shape--->3082

In [24]:
#score
np.round(model.score(X_test,y_test),4)

0.7695

In [25]:
#error
from sklearn.metrics import mean_squared_error
np.round(mean_squared_error(y_test,pred,squared=False),4)

0.459

In [26]:
#mse
from sklearn.metrics import mean_squared_error
np.round(mean_squared_error(y_test,pred),4)

0.2107

In [27]:
#mae
from sklearn.metrics import mean_absolute_error
np.round(mean_absolute_error(y_test,pred),4)

0.3599

In [28]:
#intercept
model.intercept_

-4.634579054067551

In [29]:
#coefficients 
model.coef_

array([ 8.70299192e-03,  3.01363706e-02,  1.38405821e-02, -4.72606520e-10,
        4.00117490e-03,  3.86506231e-02,  2.95177969e-01, -2.16179562e-01,
        2.05597614e-01, -1.23439800e-01, -7.71138329e-03, -5.25586228e-03,
        1.35586885e-01,  5.35092098e-03,  1.21257525e-01, -2.53525432e-02])

In [30]:
#regularization :ridge
from sklearn.linear_model import Ridge
model1 = Ridge(alpha=0.50)
model1.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=3.25726e-18): result may not be accurate.
  overwrite_a=True).T


Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [31]:
#predicting coefficents
pred1 = model1.predict(X_test)
pred1

array([6.63710861, 5.46615248, 5.67106961, 7.14239963, 4.57107235,
       7.55926117, 5.51285445, 7.58312787, 6.13265119, 8.11351271,
       4.841445  , 7.90424934, 7.73895029, 5.37488125, 6.33341983,
       6.02853889, 4.64670927, 6.2914161 , 7.09832594, 6.48605849,
       5.14467577, 7.37202323, 5.56926425, 6.57173116, 7.02171382,
       4.69300951, 4.70242118, 6.47750111, 5.73647341, 6.51282918,
       5.28533767, 6.55381765, 5.71283117, 6.71849806, 6.49945992,
       4.8499981 , 6.6992201 , 6.72886069, 6.00404529, 7.66156798,
       7.43803458, 6.25648807, 5.181765  , 6.09895053, 7.6446085 ,
       5.75440449, 5.58604242, 7.36343806, 5.74662503, 4.93980273,
       7.08653065, 4.91442112, 4.92455248, 6.68243586, 5.45458625,
       8.03055613, 7.64509776, 5.94494205, 7.55402176, 4.62360799,
       4.89805616, 7.65427963, 5.93791184, 5.63322455, 6.09573053,
       6.21511864, 6.50303424, 5.61666445])

In [32]:
#score
np.round(model1.score(X_test,y_test),4)

0.7691

In [33]:
#error
np.round(mean_squared_error(y_test,pred1,squared = False),4)

0.4594

In [34]:
#mse
np.round(mean_squared_error(y_test,pred1),4)

0.211

In [35]:
#mae
np.round(mean_absolute_error(y_test,pred1),4)

0.3603

In [36]:
model2 = Ridge()

In [37]:
#negative mae
from sklearn.model_selection import GridSearchCV
from numpy import arange
grid = dict()
grid['alpha'] = arange(0, 1, 0.01)
# define search
search = GridSearchCV(model2, grid, scoring='neg_mean_absolute_error', n_jobs=-1)
results = search.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=3.83059e-18): result may not be accurate.
  overwrite_a=True).T


In [38]:
results

GridSearchCV(cv=None, error_score=nan,
             estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=None, normalize=False, random_state=None,
                             solver='auto', tol=0.001),
             iid='deprecated', n_jobs=-1,
             param_grid={'alpha': array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.2...
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_abso

In [39]:
print('MAE: %.3f' % results.best_score_)
print('Config: %s' % results.best_params_)

MAE: -0.357
Config: {'alpha': 0.99}


In [40]:
pred3 = search.predict(X_test)

In [41]:
#error
np.round(mean_squared_error(y_test,pred3,squared = False),4)

0.4596

In [42]:
#score
np.round(search.score(X_test,y_test),4)

-0.3606

In [43]:
#mse
np.round(mean_squared_error(y_test,pred3),4)

0.2113

In [44]:
#mae
np.round(mean_absolute_error(y_test,pred3),4)

0.3606

In [45]:
# implementation of Principal Compoenet Analysis (PCA)
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
df = pca.fit_transform(X)
data1 = pd.DataFrame(data = df,columns = ['value1','value2','value3','value4','value5'])
data1.head()

value1     value2     value3     value4    value5
0 -2.666443e+07 -24.291434   2.525027   2.279527  7.141782
1  2.202317e+05 -47.319049  -6.878027 -10.092408  6.363922
2 -6.073825e+07 -39.791369  10.690541   2.818629  6.927414
3 -6.399279e+07 -19.023318  18.713367   2.583549  6.619130
4 -5.752270e+07   1.741252  -0.595162   2.675371  7.263411

In [46]:
data1.shape

(225, 5)

In [47]:
pca.explained_variance_ratio_

array([1.00000000e+00, 1.81035948e-13, 2.26542749e-14, 3.93419377e-15,
       3.05488594e-15])

In [48]:
pca.components_

array([[ 7.36439869e-08,  5.95655477e-08,  4.24639668e-08,
         1.00000000e+00,  6.67993380e-10,  2.10895787e-09,
         4.95271430e-10,  8.22423022e-10,  2.08002945e-09,
        -3.68778036e-10, -1.84271761e-09, -2.04579902e-10,
        -2.70416989e-10, -3.22735619e-10, -4.09320242e-11,
        -2.04197653e-11],
       [-7.68192081e-01, -4.34868125e-01, -4.69830494e-01,
         1.02414742e-07, -2.53725611e-04,  1.21100470e-03,
        -4.43673661e-04, -3.16931384e-04,  2.01565113e-03,
         1.61972645e-03, -3.84629191e-03, -6.96391341e-04,
         3.68770086e-04,  1.74467950e-03,  1.64595599e-03,
        -5.14841854e-04],
       [-3.30371779e-01,  8.97398906e-01, -2.90517481e-01,
        -1.67539689e-08, -3.19608496e-02,  9.71602323e-04,
        -1.38467445e-03, -1.96530243e-03, -1.98465080e-03,
        -2.78351083e-03,  5.08089664e-03,  3.89786181e-04,
         2.95958200e-03, -3.07207380e-03, -6.69634849e-03,
        -6.09978740e-04],
       [ 5.44946080e-01, -6.49490102e

In [49]:
model3 = LinearRegression()

In [50]:
X_train1,X_test1,y_train1,y_test1 = train_test_split(data1, Y, test_size=0.20, random_state=0)

In [51]:
model3.fit(X_train1,y_train1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [52]:
pred4 = model3.predict(X_test1)
pred4

array([6.74415145, 5.37218525, 5.73922425, 7.12348552, 4.80435648,
       7.51222226, 5.45653106, 7.52575434, 6.33180156, 8.07928273,
       4.72318958, 7.82542247, 7.59346557, 5.42006123, 6.38785979,
       6.25070628, 4.90854268, 6.17090295, 7.20214155, 6.62395497,
       5.26123131, 7.49392838, 5.37494761, 6.52945953, 7.07935727,
       5.05624855, 4.94304433, 6.51304445, 5.86867937, 6.56423806,
       5.3004739 , 6.65229785, 5.66871499, 6.75333992, 6.4277885 ,
       5.00158968, 6.56532694, 6.76889844, 5.98964172, 7.63289833,
       7.25557272, 6.47468957, 5.42512963, 6.25117109, 7.59100235])

In [53]:
y_test1

111    6.6
101    6.0
197    6.2
183    7.4
75     2.9
64     7.5
145    5.9
137    7.4
207    6.6
168    8.0
143    5.2
166    8.1
107    7.3
8      5.8
126    6.3
156    6.2
108    5.3
5      6.7
44     7.3
139    6.3
176    5.3
153    6.4
187    6.2
179    6.7
106    6.9
125    5.5
97     3.8
37     6.7
12     6.1
202    6.8
161    5.6
134    6.0
104    6.1
55     6.6
89     6.2
18     4.9
15     6.5
149    6.9
7      6.1
159    7.7
178    7.0
90     6.8
144    5.7
92     6.5
63     7.4
Name: IMDb, dtype: float64

In [54]:
np.round(mean_squared_error(y_test1,pred4,squared = False),4)

0.4824

In [55]:
np.round(model3.score(X_test1,y_test1),4)

0.7557

In [56]:
np.round(mean_squared_error(y_test,pred3),3)


0.211

In [57]:
np.round(mean_absolute_error(y_test,pred3),4)

0.3606